# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.5"
  - "3.6"
  #- "nightly" # points to the latest development branch
# command to install dependencies
install:
- "pip install -r requirements.txt"
- "pip install -r test-requirements.txt"
# command to run tests
script: nosetests
